# Generated by Django 4.0.2 on 2022-03-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_branch_registration_email_branch_registration_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_status',
            name='json',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='test_status',
            name='json_testerscreenshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
