# Generated by Django 4.0.2 on 2022-03-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_test_status_json_test_status_json_testerscreenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_status',
            name='files',
        ),
    ]
